

/*
MAVLink protocol implementation (auto-generated by mavgen.py)

Note: this file has been auto-generated. DO NOT EDIT
*/

using System;
using System.Collections;
using System.Collections.Generic;
    
namespace MavLink
{
    public static class MavlinkSettings
    {
		public const string WireProtocolVersion = "1.0";
		public const byte ProtocolMarker = 0xfe;
		public const bool CrcExtra = true;
		public const bool IsLittleEndian = true;
    }
    
    public delegate MavlinkMessage MavlinkPacketDeserializeFunc(byte[] bytes, int offset);

    //returns the message ID, offset is advanced by the number of bytes used to serialize
    public delegate int MavlinkPacketSerializeFunc(byte[] bytes, ref int offset, object mavlinkPacket);
 
    public class MavPacketInfo
    {
        public MavlinkPacketDeserializeFunc Deserializer;
        public int [] OrderMap;
        public byte CrcExtra;

         public MavPacketInfo(MavlinkPacketDeserializeFunc deserializer, byte crcExtra)
         {
             this.Deserializer = deserializer;
             this.CrcExtra = crcExtra;
         }
    }
 
    public static class MavLinkSerializer
    {
        public static void SetDataIsLittleEndian(bool isLittle)
        {
            bitconverter.SetDataIsLittleEndian(isLittle);
        }
    
        private static readonly FrameworkBitConverter bitconverter = new FrameworkBitConverter(); 
    
        public static Dictionary<int, MavPacketInfo> Lookup = new Dictionary<int, MavPacketInfo>
        {
			{0, new MavPacketInfo(Deserialize_SET_RGB, 254)},
			{1, new MavPacketInfo(Deserialize_angle, 165)},
		};

		internal static MavlinkMessage Deserialize_SET_RGB(byte[] bytes, int offset)
		{
			return new Msg_set_rgb
			{
				led_number = bytes[offset + 0],
				led_strip_colors =  ByteArrayUtil.ToUInt8(bytes, offset + 1, 36),
			};
		}

		internal static MavlinkMessage Deserialize_angle(byte[] bytes, int offset)
		{
			return new Msg_angle
			{
				angle = bitconverter.ToSingle(bytes, offset + 0),
			};
		}

		internal static int Serialize_SET_RGB(this Msg_set_rgb msg, byte[] bytes, ref int offset)
		{
			bytes[offset + 0] = msg.led_number;
			ByteArrayUtil.ToByteArray(msg.led_strip_colors, bytes, offset + 1, 36);
			offset += 37;
			return 0;
		}

		internal static int Serialize_angle(this Msg_angle msg, byte[] bytes, ref int offset)
		{
			bitconverter.GetBytes(msg.angle, bytes, offset + 0);
			offset += 4;
			return 1;
		}
	}

}

