/*
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: ledwheel.xml

Note: this file has been auto-generated. DO NOT EDIT
*/

using System;

    
using System.Reflection;    
    
[assembly: AssemblyTitle("Mavlink Classes")]
[assembly: AssemblyDescription("Generated Message Classes for Mavlink. See http://qgroundcontrol.org/mavlink/start")]
[assembly: AssemblyProduct("Mavlink")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

    namespace MavLink
{

}

    
   
namespace MavLink
{

    public abstract class MavlinkMessage
    {
        public abstract int Serialize(byte[] bytes, ref int offset);
    }

	/// <summary>
	/// Set rgb value in matrix
	/// </summary>
	public class Msg_set_rgb : MavlinkMessage
    {

		/// <summary>
		/// 
		/// </summary>
		public byte led_number;

		/// <summary>
		/// 
		/// </summary>
		public byte[] led_strip_colors; // Array size 36

        public override int Serialize(byte[] bytes, ref int offset)
            {
                return MavLinkSerializer.Serialize_SET_RGB(this, bytes, ref offset);
            }        
	}


	/// <summary>
	/// Gets led wheel angle
	/// </summary>
	public class Msg_angle : MavlinkMessage
    {

		/// <summary>
		/// 
		/// </summary>
		public float angle;

        public override int Serialize(byte[] bytes, ref int offset)
            {
                return MavLinkSerializer.Serialize_ANGLE(this, bytes, ref offset);
            }        
	}

}

