/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SET_RGB PACKING
package com.MAVLink.test\ledwheel;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Set rgb value in matrix
*/
public class msg_set_rgb extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SET_RGB = 0;
    public static final int MAVLINK_MSG_LENGTH = 37;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SET_RGB;


      
    /**
    * 
    */
    public short led_number;
      
    /**
    * 
    */
    public short led_strip_colors[] = new short[36];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket();
        packet.len = MAVLINK_MSG_LENGTH;
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SET_RGB;
              
        packet.payload.putUnsignedByte(led_number);
              
        
        for (int i = 0; i < led_strip_colors.length; i++) {
            packet.payload.putUnsignedByte(led_strip_colors[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a set_rgb message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.led_number = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.led_strip_colors.length; i++) {
            this.led_strip_colors[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_set_rgb(){
        msgid = MAVLINK_MSG_ID_SET_RGB;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_set_rgb(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SET_RGB;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SET_RGB -"+" led_number:"+led_number+" led_strip_colors:"+led_strip_colors+"";
    }
}
        